/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Random;

/**
 *
 * @author andreea
 */
public class Fractal_Canvas extends javax.swing.JFrame {

    /**
     * Creates new form Fractal_Canvas
     */
    public Fractal_Canvas() {
        initComponents();
    }
    int x1;
    int y1;
    int x2;
    int y2;
    int x3;
    int y3;
    int x4;
    int y4;
    Random rand = new Random();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fractal1 = new javax.swing.JButton();
        fractal5 = new javax.swing.JButton();
        fractal2 = new javax.swing.JButton();
        fractal6 = new javax.swing.JButton();
        fractal3 = new javax.swing.JButton();
        fractal7 = new javax.swing.JButton();
        fractal4 = new javax.swing.JButton();
        fractal8 = new javax.swing.JButton();
        seeButton = new javax.swing.JButton();
        newPaintsButton = new javax.swing.JButton();
        bestFractals = new javax.swing.JButton();
        grade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 22, 470, 390));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        fractal1.setText("Fractal 1");
        fractal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal1ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        fractal1.getAccessibleContext().setAccessibleDescription("");

        fractal5.setText("Fractal 5");
        fractal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal5ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        fractal2.setText("Fractal 2");
        fractal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal2ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        fractal6.setText("Fractal 6");
        fractal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal6ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, -1, -1));

        fractal3.setText("Fractal 3");
        fractal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal3ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        fractal7.setText("Fractal 7");
        fractal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal7ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        fractal4.setText("Fractal 4");
        fractal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal4ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        fractal8.setText("Fractal 8");
        fractal8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fractal8ActionPerformed(evt);
            }
        });
        getContentPane().add(fractal8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        seeButton.setText("See the paints");
        seeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(seeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 24, -1, -1));

        newPaintsButton.setText("New paints");
        newPaintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaintsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newPaintsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 102, -1));

        bestFractals.setText("Best paintings");
        bestFractals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestFractalsActionPerformed(evt);
            }
        });
        getContentPane().add(bestFractals, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        grade.setBackground(new java.awt.Color(153, 153, 153));
        grade.setText("Please give some grades");
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });
        getContentPane().add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 150, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\andreea\\Desktop\\Facultate+CV\\test_licenta\\black fractal.PNG")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<Project> firstParent, secondParent, oldGeneration, newGeneration, newPaintings, newPaintings2, firstChild, secondChild;
    //ArrayList<Project> figures;
    Project figures, second;

    Random random = new Random();
    int grades = 0, limit = 100;

    Individual generation = new Individual();

    Fractals_shapes fractals;
    //Project coordinates;

    //ArrayList<Project> fractals;

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_gradeActionPerformed

    private void seeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeButtonActionPerformed
        // TODO add your handling code here:

        firstParent = new ArrayList<Project>();
        secondParent = new ArrayList<Project>();
        oldGeneration = new ArrayList<Project>(limit);
        newGeneration = new ArrayList<Project>(limit);
        newPaintings = new ArrayList<Project>(limit); //first array with childs
        newPaintings2 = new ArrayList<Project>(limit); //second array with childs

        for (int i = 0; i < limit; i++) {

            x1 = random.nextInt(400);
            y1 = random.nextInt(350);
            x2 = random.nextInt(400);
            y2 = random.nextInt(350);
            x3 = random.nextInt(400);
            y3 = random.nextInt(350);
            x4 = random.nextInt(400);
            y4 = random.nextInt(350);

            oldGeneration.add(new Project(x1, y1, x2, y2, x3, y3, x4, y4));

        }
        System.out.println("fractals created");
        figures = oldGeneration.get(0);

        //fractals = new ArrayList<Project>(7);
//        for (int i = 0; i < 8; i++) {
//
//            x1 = rand.nextInt(400);
//            y1 = rand.nextInt(350);
//            x2 = rand.nextInt(400);
//            y2 = rand.nextInt(350);
//            x3 = rand.nextInt(400);
//            y3 = rand.nextInt(350);
//            x4 = rand.nextInt(400);
//            y4 = rand.nextInt(350);
//            fractals.add(new Project(x1, y1, x2, y2, x3, y3, x4, y4));
//            System.out.println("fractal " + i + " created");
//
//        }
        fractals = new Fractals_shapes();

        Graphics g = jPanel1.getGraphics();
        fractals.drawFractals(g, oldGeneration.get(0).getX1(), oldGeneration.get(0).getY1(), oldGeneration.get(0).getX2(), oldGeneration.get(0).getY2(), oldGeneration.get(0).getX3(), oldGeneration.get(0).getY3(), oldGeneration.get(0).getX4(), oldGeneration.get(0).getY4(), 4);

        Graphics g1 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g1, oldGeneration.get(0).getX1(), oldGeneration.get(0).getY1(), oldGeneration.get(0).getX2(), oldGeneration.get(0).getY2(), oldGeneration.get(0).getX3(), oldGeneration.get(0).getY3(), oldGeneration.get(0).getX4(), oldGeneration.get(0).getY4(), 0.25);


    }//GEN-LAST:event_seeButtonActionPerformed

    private void newPaintsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaintsButtonActionPerformed
        // TODO add your handling code here:

        repaint();
    }//GEN-LAST:event_newPaintsButtonActionPerformed

    private void fractal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal1ActionPerformed
        // TODO add your handling code here:

        Graphics g = jPanel1.getGraphics();
        fractals.drawFractals(g, oldGeneration.get(0).getX1(), oldGeneration.get(0).getY1(), oldGeneration.get(0).getX2(), oldGeneration.get(0).getY2(), oldGeneration.get(0).getX3(), oldGeneration.get(0).getY3(), oldGeneration.get(0).getX4(), oldGeneration.get(0).getY4(), 4);

        Graphics g1 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g1, oldGeneration.get(0).getX1(), oldGeneration.get(0).getY1(), oldGeneration.get(0).getX2(), oldGeneration.get(0).getY2(), oldGeneration.get(0).getX3(), oldGeneration.get(0).getY3(), oldGeneration.get(0).getX4(), oldGeneration.get(0).getY4(), 0.25);


    }//GEN-LAST:event_fractal1ActionPerformed

    private void fractal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal5ActionPerformed

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(4).getX1(), oldGeneration.get(4).getY1(), oldGeneration.get(4).getX2(), oldGeneration.get(4).getY2(), oldGeneration.get(4).getX3(), oldGeneration.get(4).getY3(), oldGeneration.get(4).getX4(), oldGeneration.get(4).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(4).getX1(), oldGeneration.get(4).getY1(), oldGeneration.get(4).getX2(), oldGeneration.get(4).getY2(), oldGeneration.get(4).getX3(), oldGeneration.get(4).getY3(), oldGeneration.get(4).getX4(), oldGeneration.get(4).getY4(), 0.25);

    }//GEN-LAST:event_fractal5ActionPerformed

    private void fractal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal2ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(1).getX1(), oldGeneration.get(1).getY1(), oldGeneration.get(1).getX2(), oldGeneration.get(1).getY2(), oldGeneration.get(1).getX3(), oldGeneration.get(1).getY3(), oldGeneration.get(1).getX4(), oldGeneration.get(1).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(1).getX1(), oldGeneration.get(1).getY1(), oldGeneration.get(1).getX2(), oldGeneration.get(1).getY2(), oldGeneration.get(1).getX3(), oldGeneration.get(1).getY3(), oldGeneration.get(1).getX4(), oldGeneration.get(1).getY4(), 0.25);

    }//GEN-LAST:event_fractal2ActionPerformed

    private void fractal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal3ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(2).getX1(), oldGeneration.get(2).getY1(), oldGeneration.get(2).getX2(), oldGeneration.get(2).getY2(), oldGeneration.get(2).getX3(), oldGeneration.get(2).getY3(), oldGeneration.get(2).getX4(), oldGeneration.get(2).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(2).getX1(), oldGeneration.get(2).getY1(), oldGeneration.get(2).getX2(), oldGeneration.get(2).getY2(), oldGeneration.get(2).getX3(), oldGeneration.get(2).getY3(), oldGeneration.get(2).getX4(), oldGeneration.get(2).getY4(), 0.25);

    }//GEN-LAST:event_fractal3ActionPerformed

    private void fractal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal4ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(3).getX1(), oldGeneration.get(3).getY1(), oldGeneration.get(3).getX2(), oldGeneration.get(3).getY2(), oldGeneration.get(3).getX3(), oldGeneration.get(3).getY3(), oldGeneration.get(3).getX4(), oldGeneration.get(3).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(3).getX1(), oldGeneration.get(3).getY1(), oldGeneration.get(3).getX2(), oldGeneration.get(3).getY2(), oldGeneration.get(3).getX3(), oldGeneration.get(3).getY3(), oldGeneration.get(3).getX4(), oldGeneration.get(3).getY4(), 0.25);

    }//GEN-LAST:event_fractal4ActionPerformed

    private void fractal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal6ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(5).getX1(), oldGeneration.get(5).getY1(), oldGeneration.get(5).getX2(), oldGeneration.get(5).getY2(), oldGeneration.get(5).getX3(), oldGeneration.get(5).getY3(), oldGeneration.get(5).getX4(), oldGeneration.get(5).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(5).getX1(), oldGeneration.get(5).getY1(), oldGeneration.get(5).getX2(), oldGeneration.get(5).getY2(), oldGeneration.get(5).getX3(), oldGeneration.get(5).getY3(), oldGeneration.get(5).getX4(), oldGeneration.get(5).getY4(), 0.25);


    }//GEN-LAST:event_fractal6ActionPerformed

    private void fractal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal7ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(6).getX1(), oldGeneration.get(6).getY1(), oldGeneration.get(6).getX2(), oldGeneration.get(6).getY2(), oldGeneration.get(6).getX3(), oldGeneration.get(6).getY3(), oldGeneration.get(6).getX4(), oldGeneration.get(6).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(6).getX1(), oldGeneration.get(6).getY1(), oldGeneration.get(6).getX2(), oldGeneration.get(6).getY2(), oldGeneration.get(6).getX3(), oldGeneration.get(6).getY3(), oldGeneration.get(6).getX4(), oldGeneration.get(6).getY4(), 0.25);


    }//GEN-LAST:event_fractal7ActionPerformed

    private void fractal8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fractal8ActionPerformed
        // TODO add your handling code here:

        Graphics g4 = jPanel1.getGraphics();
        fractals.drawFractals(g4, oldGeneration.get(7).getX1(), oldGeneration.get(7).getY1(), oldGeneration.get(7).getX2(), oldGeneration.get(7).getY2(), oldGeneration.get(7).getX3(), oldGeneration.get(7).getY3(), oldGeneration.get(7).getX4(), oldGeneration.get(7).getY4(), 4);

        Graphics g5 = jPanel2.getGraphics();
        fractals.drawFirstIteration(g5, oldGeneration.get(7).getX1(), oldGeneration.get(7).getY1(), oldGeneration.get(7).getX2(), oldGeneration.get(7).getY2(), oldGeneration.get(7).getX3(), oldGeneration.get(7).getY3(), oldGeneration.get(7).getX4(), oldGeneration.get(7).getY4(), 0.25);


    }//GEN-LAST:event_fractal8ActionPerformed

    private void bestFractalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestFractalsActionPerformed
        // TODO add your handling code here:

        int k = 0;
        while (k < 10) {

            k++;
            firstParent = new ArrayList<>();
            secondParent = new ArrayList<>();
            firstChild = new ArrayList<>();
            secondChild = new ArrayList<>();
            newPaintings.clear();
            newPaintings2.clear();

            for (int i = 0; i < 100; i++) {
                //System.out.println("i: " + i);
                figures = oldGeneration.get(i);
                oldGeneration.get(i).setGrade(generation.fitness(figures));
            }

            for (int i = 0; i < 100; i++) {
                int newX1 = random.nextInt(400);
                int newY1 = random.nextInt(350);
                int newX2 = random.nextInt(400);
                int newY2 = random.nextInt(350);
                int newX3 = random.nextInt(400);
                int newY3 = random.nextInt(350);
                int newX4 = random.nextInt(400);
                int newY4 = random.nextInt(350);

                newPaintings.add(new Project(newX1, newY1, newX2, newY2, newX3, newY3, newX4, newY4));
                newPaintings2.add(new Project(newX1, newY1, newX2, newY2, newX3, newY3, newX4, newY4));
            }

            generation.bubbleSort(oldGeneration);

            for (int i = 0; i < 100; i++) {
                //System.out.println("i: " + i);
                figures = oldGeneration.get(i);
            }

            for (int i = 0; i < 100; i++) {

                firstParent.clear();
                firstParent.add(generation.tournamentSelection(oldGeneration));

                secondParent.clear();
                secondParent.add(generation.tournamentSelection(oldGeneration));

                figures = newPaintings.get(i);
                generation.crossover(firstParent, secondParent);
                generation.mutate(firstChild);
                generation.mutate(secondChild);

            }

            oldGeneration.clear();
            oldGeneration.addAll(newPaintings);

        }

        for (int i = 0; i < 100; i++) {

            figures = oldGeneration.get(i);
            oldGeneration.get(i).setGrade(generation.fitness(figures));
        }
        generation.bubbleSort(oldGeneration);

        for (int i = 0; i < 100; i++) {
            //System.out.println("i: " + i);
            figures = oldGeneration.get(i);
            oldGeneration.get(i).setGrade(generation.fitness(figures));
            System.out.println("Fractals: " + i);
            System.out.println("Grade: " + oldGeneration.get(i).getGrade());
            
        }
        System.out.print("\n");

    }//GEN-LAST:event_bestFractalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fractal_Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fractal_Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fractal_Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fractal_Canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fractal_Canvas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bestFractals;
    private javax.swing.JButton fractal1;
    private javax.swing.JButton fractal2;
    private javax.swing.JButton fractal3;
    private javax.swing.JButton fractal4;
    private javax.swing.JButton fractal5;
    private javax.swing.JButton fractal6;
    private javax.swing.JButton fractal7;
    private javax.swing.JButton fractal8;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton newPaintsButton;
    private javax.swing.JButton seeButton;
    // End of variables declaration//GEN-END:variables

}
